In [183]:
import pandas as pd
import tensorflow as tf
from joblib import load

In [184]:
query="30.287235_-97.742271_78660_1.98_2013_1_2.6666667_3_6185_1768_0_0_4_2_1_2_1_1_0_0_0_0_"
query_list=query.split("_")
query_list.pop(-1)
query_list
for i,query in enumerate(query_list):
    if query=="":
        query_list[i]=0
    query_list[i]=float(query_list[i])
query_list

[30.287235,
 -97.742271,
 78660.0,
 1.98,
 2013.0,
 1.0,
 2.6666667,
 3.0,
 6185.0,
 1768.0,
 0.0,
 0.0,
 4.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [185]:
len(query_list)

22

In [186]:
# query_list=[30.43063164, -97.66307831, 'Other', 1.98, 2012, 5, 2.666666667, 3,
#        6011.0, 2601, 1, 3, 4, 3.0, 2, 2, True, True, False, False, 0, 0]
# query_list

In [187]:
len(query_list)

22

In [188]:
zips=['78702','78703','78704','78717','78721',
 '78723','78724','78727','78728','78729',
 '78730','78731','78732','78733','78735',
 '78737','78739','78741','78744','78745',
 '78747','78748','78749','78750','78753',
 '78754','78757','78758','78759','Other']

In [189]:
zipcode=query_list[2]
if (zipcode in zips)==False:
    zipcode="Other"
zipcode_index=zips.index(zipcode)
zipcode_dummy=[0]*zipcode_index+[1]+[0]*(len(zips)-1-zipcode_index)
print(zipcode_dummy)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


In [190]:
query_list.pop(2)
query_list=query_list+zipcode_dummy
query_list

query_list

[30.287235,
 -97.742271,
 1.98,
 2013.0,
 1.0,
 2.6666667,
 3.0,
 6185.0,
 1768.0,
 0.0,
 0.0,
 4.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1]

In [191]:
len(query_list)

51

In [192]:
loaded_model = load('../Resources/nn/std_scaler.bin')
query_list_scaled=loaded_model.transform([query_list])
query_list_scaled

array([[-0.03834704,  0.43301625, -0.26801489,  1.13309392, -0.81752339,
        -1.67067543, -0.00888214, -0.01048531, -0.42234815, -0.67645668,
        -0.56984224,  0.66977697, -0.69970027, -0.88973225,  0.58037891,
         0.12784597,  0.09468152, -0.54027422, -0.29087832, -0.08566867,
        -0.04903777, -0.16118296, -0.14314829, -0.2189785 , -0.18794504,
        -0.12712619, -0.1929549 , -0.12160084, -0.1654834 , -0.12346843,
        -0.15041284, -0.12891857, -0.18307645, -0.20170333, -0.1158282 ,
        -0.13988206, -0.20852408, -0.2059592 , -0.11932344, -0.18151548,
        -0.27325482, -0.15737073, -0.2921341 , -0.23245717, -0.13955156,
        -0.17434041, -0.1654834 , -0.18307645, -0.16519982, -0.19541842,
         2.97727296]])

In [193]:
new_model = tf.keras.models.load_model("../Resources/nn/neural_network.h5")


In [194]:
new_model.predict(query_list_scaled)

1/1 [==============================] - 0s 158ms/step


array([[178988.44]], dtype=float32)

In [174]:
new_model.predict(query_list_scaled)

1/1 [==============================] - 0s 57ms/step


array([[378867.2]], dtype=float32)

In [175]:
new_model.predict(query_list_scaled)

1/1 [==============================] - 0s 56ms/step


array([[378867.2]], dtype=float32)

In [176]:
new_model.predict(query_list_scaled)

1/1 [==============================] - 0s 60ms/step


array([[378867.2]], dtype=float32)

In [177]:
new_model.predict(query_list_scaled)

1/1 [==============================] - 0s 57ms/step


array([[378867.2]], dtype=float32)

In [179]:
price=new_model.predict(query_list_scaled)

1/1 [==============================] - 0s 62ms/step


In [180]:
price

array([[378867.2]], dtype=float32)

In [182]:
price[0][0]

378867.2